# Generated by Django 2.2.13 on 2020-07-29 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200704_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Article', to=settings.AUTH_USER_MODEL),
        ),
    ]
